services:
  - type: web
    name: husky-ambassador-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn HA_dash:app.server"
    autoDeploy: true